spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    redis:
      host: localhost
      port: 6379
#      password: 1234
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms


resilience4j:
  ratelimiter:
    instances:
      fixedWindow:
        limitForPeriod: 1          # 윈도우 내 허용 요청 수 (Limit)
        limitRefreshPeriod: 1s     # 윈도우 크기 (1분 = 60초) -> 주기적으로 카운터를 리셋하는 고정된 시간
        timeoutDuration: 0          # 요청이 거부될 때 대기 시간 없이 즉시 실패